### ISSUE TITLE
Reconnecting doesn't work

### ISSUE THREAD

**Issue by arjaz** [wowica/xogmios#33]
From the docs `Returning {:reconnect, interval_in_ms} will attempt a reconnection after interval_in_ms`

This doesn't seem to work and gives a `** (CaseClauseError) no case clause matching: {:reconnect, 2500}` error.
The actual function seems to expect a `{:reconnect, ms, new_state}` instead, but forwarding the old state gives the following error:
```
[error] Supervisor received unexpected message: {:connected,
 {:websocket_req, :ws, ~c"0.0.0.0", 1337, ~c"/", 5000,
  #Reference<0.318507591.820510723.76767>, 1, #Port<0.20>,
  {:transport, :gen_tcp, :tcp, :tcp_closed, :tcp_error,
   [mode: :binary, active: true, packet: 0]}, "xxxxxxxx==",
  :undefined, 1, 1, :undefined, :undefined}}
```

**Comment by caike** [comment]
Thanks for reporting. The fix to the callback and docs are ready but I am still investigating how to get rid of this error. I've verified the reconnection via `{:reconnect, interval, new_state}` does work, though 👍

**Comment by arjaz** [comment]
I don't think that you actually get blocks after reconnecting in 0.5.0
