### ISSUE TITLE
Ogmios connections leak

### ISSUE THREAD

**Issue by arjaz** [wowica/xogmios#46]
I think the reconnect during the network sync doesn't terminate the connections correctly.

With Xogmios trying to reconnect the number grows indefinitely.
![image](https://github.com/user-attachments/assets/558bf9bc-b951-4360-a5c3-d88ddd00248e)
![image](https://github.com/user-attachments/assets/fca24f1a-90b2-4ad8-8a62-3be7b4974f11)

As soon as I terminate the Xogmios application all open connections are dropped.
![image](https://github.com/user-attachments/assets/1d358cc4-1214-4912-b280-5f46eba0ae22)

**Comment by caike** [comment]
@arjaz  Thanks for reporting the issue 🙏  

Mind checking if the `fix-reconnection-leak` branch works for you ?

```elixir
{:xogmios, github: "wowica/xogmios", branch: "fix-reconnection-leak"}
```

Then I can merge this PR and push an update to hex

**Comment by arjaz** [comment]
Yes, can confirm that there are no piling up of clients with the branch. Thank you!

**Comment by caike** [comment]
Closed with https://github.com/wowica/xogmios/pull/47
